// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5DJOPD2k7pt969WanTSWsWBMCjGl6KzA',
    appId: '1:90600107249:web:f7592a98c23f0fc5de8d50',
    messagingSenderId: '90600107249',
    projectId: 'crew-portal-flutter',
    authDomain: 'crew-portal-flutter.firebaseapp.com',
    storageBucket: 'crew-portal-flutter.appspot.com',
    measurementId: 'G-0BMMZBFMFX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEHalUWefjeAR4gbc6G8sMsGELdj7ZMx4',
    appId: '1:90600107249:android:f5d40ab0a580df9ede8d50',
    messagingSenderId: '90600107249',
    projectId: 'crew-portal-flutter',
    storageBucket: 'crew-portal-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4cXZhueZzqKP3KamA3818bwQsvrcsk4s',
    appId: '1:90600107249:ios:c07b0fe9666d2cd5de8d50',
    messagingSenderId: '90600107249',
    projectId: 'crew-portal-flutter',
    storageBucket: 'crew-portal-flutter.appspot.com',
    iosClientId: '90600107249-tvo2ahiklosggps00vrdnis7l9j8rg77.apps.googleusercontent.com',
    iosBundleId: 'com.example.crewPortalFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4cXZhueZzqKP3KamA3818bwQsvrcsk4s',
    appId: '1:90600107249:ios:c07b0fe9666d2cd5de8d50',
    messagingSenderId: '90600107249',
    projectId: 'crew-portal-flutter',
    storageBucket: 'crew-portal-flutter.appspot.com',
    iosClientId: '90600107249-tvo2ahiklosggps00vrdnis7l9j8rg77.apps.googleusercontent.com',
    iosBundleId: 'com.example.crewPortalFlutter',
  );
}
